### ISSUE TITLE
Usage with multiple SCS-Binders

### ISSUE THREAD

**Issue by MikeR13** [solacecommunity/spring-solace-leader-election#4]
In a project I use several Binders e.g. spring.cloud.stream.binders.solace1. This does not work, The framework tries to connect with the default JCSMPProperties.
It would be nice to have a configuration where I can reference a special binder that is needed for the leader election.

**Comment by GreenRover** [comment]
One of the design decisions here is to make this a spring plugin not s spring cloud stream.
To achieve compatibility for as many projects as possible.
You describe a spring cloud stream functionality.

So a feature like this is not possible.
