### ISSUE TITLE
[Java Version]: the java version 11 is outdated and should be lifted 

### ISSUE THREAD

**Issue by MikeR13** [solacecommunity/spring-solace-leader-election#9]
### Feature Description

 the java version 11 is outdated and should be lifted at least to 17

### Use Case

EOL Java 11

### Proposed Solution

<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
or
<maven.compiler.source>21</maven.compiler.source>
<maven.compiler.target>21</maven.compiler.target>

**Comment by GreenRover** [comment]
Work is already in progress:
https://flow.sbb.ch/browse/STTRS-1583

**Comment by helios57** [comment]
Done
